'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код был создан программным средством.
'
'     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
'     код создан повторно.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Register

    '''<summary>
    '''Элемент управления RegisterUser.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents RegisterUser As Global.System.Web.UI.WebControls.CreateUserWizard

    '''<summary>
    '''Элемент управления RegisterUserWizardStep.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents RegisterUserWizardStep As Global.System.Web.UI.WebControls.CreateUserWizardStep
End Class
